---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.6
    driver:
      network:
      - ["forwarded_port", {guest: 443, host: 4433}]
      customize:
        cpus: 2
        memory: 2048

suites:
  - name: default
    run_list:
      - recipe[chef-server::default]
    attributes:
